version: '3.4'

services:
    cadastrodecaminhao.visualizacaomvc:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ConnectionStrings__CadastroDeCaminhaoVisualizacaoMVCContextConnection=Server=caminhaoContainer; User Id=admin; Database=banco_caminhao; Password=admin123!
        depends_on:
            - caminhaoContainer
        ports:
            - "80"
            - "443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    caminhaoContainer:
        container_name: caminhaoContainer
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123!
            - POSTGRES_DB=banco_caminhao
        restart: 
            always
        ports:
            - '5432:5432'
        volumes:
            - data_caminhao:/var/lib/postgresql/data/